export const GET_ALL_NEMU_SUCCESS = "GET_ALL_NEMU_SUCCESS"
export const SAVE_NEMU_SUCCESS = "SAVE_NEMU_SUCCESS"
export const GET_ALL_NEMU_OPTION_SUCCESS = "GET_ALL_NEMU_OPTION_SUCCESS"
export const GET_ALL_NEMU_ERROR = "GET_ALL_NEMU_ERROR"

export const GET_NEMU_FILTER_SUCCESS = "GET_NEMU_FILTER_SUCCESS"

